### ISSUE TITLE
`test` folder included at the root of the python folder

### ISSUE THREAD

**Issue by hadim** [conda-forge/gpytorch-feedstock#12]
The `test` folder is included during the installation, creating warning messages when it conflicts with other packages:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/noarch::gpytorch-1.5.1-pyhd8ed1ab_0, conda-forge/noarch::botorch-0.2.2-py_0
  path: 'lib/python3.9/site-packages/test/optim/__pycache__/__init__.cpython-39.pyc'
```

xref with https://github.com/conda-forge/botorch-feedstock/issues/9

**Comment by hadim** [comment]
ping @conda-forge/gpytorch

**Comment by ngam** [comment]
thanks @hadim --- I am not sure what is causing this. However, I am also confused why "test" is imported here:

https://github.com/conda-forge/gpytorch-feedstock/blob/ba3a65e4b8e4a9fc95cdf1b796a094f250cf87a4/recipe/meta.yaml#L42

Can @conda-forge/gpytorch comment on why you have a pretty vague import? But I am not sure how this can lead to your specific problem...

**Comment by ngam** [comment]
also, can you try to have botorch and gpytorch in a fresh env alone? I notice you have botorch 0.2.2, and we currently are running at 0.5.1

**Comment by hadim** [comment]
I checked in the 0.5.1 package and the `test` folder is still here: https://anaconda.org/conda-forge/botorch/0.5.1/download/noarch/botorch-0.5.1-pyhd8ed1ab_0.tar.bz2

**Comment by ngam** [comment]
Okay, both the packages have that --- as well as the packages from the pytorch channel. I think it is safe to delete these folders, but let's first hear from others.

**Comment by ngam** [comment]
@hadim we've removed the test from botorch (fingers crossed) so could you test again to see if it works in a bit?

**Comment by hadim** [comment]
All good, the test folder is not in the package anymore: https://anaconda.org/conda-forge/botorch/0.5.1/download/noarch/botorch-0.5.1-pyhd8ed1ab_1.tar.bz2

Ideally, that should be fixed upstream during the pip package building using `MANIFEST.in` to exclude that folder (this folder is likely in the pip package as well).

Anyway on the conda side, all good.

**Comment by hadim** [comment]
(all good for botorch but not gpytorch)

**Comment by ngam** [comment]
> Ideally, that should be fixed upstream during the pip package building using `MANIFEST.in` to exclude that folder (this folder is likely in the pip package as well).

Agree. I will look into adding that in a patch for now and still utilizing the contents of that test folder for testing. Maybe that's why they're importing it here on L42

**Comment by ngam** [comment]
Moot as of update.

**Comment by hadim** [comment]
@ngam Why closing here? The conda package at https://anaconda.org/conda-forge/gpytorch/1.6.0/download/noarch/gpytorch-1.6.0-pyhd8ed1ab_0.tar.bz2 still contain this folder `/site-packages/test/`

**Comment by ngam** [comment]
it does????????

**Comment by ngam** [comment]
UGH. Okay, I am now a maintainer in this feedstock, so I will fix it very soon, sorry I should've checked.

Btw, I filed two issues upstream and they both fixed them, but maybe they didn't include that in the 1.6.0 release here...

**Comment by hadim** [comment]
xref with https://github.com/cornellius-gp/gpytorch/pull/1855#issuecomment-992547367
